name: Reiseplaner
acronym: RP
language: en
members:
  ai:vibe@joy:
    capabilities:
      conceive:
        max-interaction-level: confirmed
      plan:
        max-interaction-level: confirmed
      design:
        max-interaction-level: confirmed
      implement:
        max-interaction-level: confirmed
      test:
        max-interaction-level: confirmed
      review:
        max-interaction-level: confirmed
      document:
        max-interaction-level: confirmed
      jobs:
        max-interaction-level: confirmed
      create:
        max-interaction-level: confirmed
      assign:
        max-interaction-level: confirmed
      manage:
        max-interaction-level: confirmed
      delete:
        max-interaction-level: confirmed
    adapter: vibe
    verify_key: 11779a611349717c0f6f2a69c5838d080fc2b9096a873f77c1733fbe288bbad4
    attestation:
      attester: philipp@joyint.com
      signed_fields:
        email: ai:vibe@joy
        capabilities:
          conceive:
            max-interaction-level: confirmed
          plan:
            max-interaction-level: confirmed
          design:
            max-interaction-level: confirmed
          implement:
            max-interaction-level: confirmed
          test:
            max-interaction-level: confirmed
          review:
            max-interaction-level: confirmed
          document:
            max-interaction-level: confirmed
          jobs:
            max-interaction-level: confirmed
          create:
            max-interaction-level: confirmed
          assign:
            max-interaction-level: confirmed
          manage:
            max-interaction-level: confirmed
          delete:
            max-interaction-level: confirmed
      signed_at: 2026-10-10T07:37:45.634654208Z
      signature: c029b1863e0ffcf3c2481977080591bf4981ff0c8da0c7d89aadfa5ee4f4d994180bd221b87939092fa27d9fbeeb2adaa8efe1f17e065038931772687c2ab10a
  philipp@joyint.com:
    capabilities: all
    verify_key: 51dbca6b131fff6f06f3c5523dcb31d55eebef7f585ec56db53f56ec568699c9
    kdf_nonce: 41f103b535f118cf1921985a9106b2f9b0af011c3e2f8f824fc97863ece2368a
    seed_wrap_passphrase: e4e572ea90b91da7667843d72e3449d9c3388bec30185094ac5801682fe3c5055cc59b0f674dd846e7015950b5d93a771e0d4521b241c711584b46bf
    seed_wrap_recovery: 409afb3ae25bc6e8be4bb343de630c06167c7accc1ce908c4efa36b59d1491c88f2a30491be204dc32309339ac771118f3e79db4625457686fc2d24e
    ai_delegations:
      ai:vibe@joy:
        delegation_verifier: 992a8c629e43d15e2cffabe9b7dbbcd5ccdcd4680f443b6e14b3f9dbce754033
        delegation_salt: 63ba44b492b00fcad5d4167ebde262403978fe2ac675abcc7069931b6a0c7835
        created: 2026-10-10T07:37:17.182868559Z
created: 2026-10-02T18:27:20.788533027Z
